config/routes.rb
Spanishswipe::Application.routes.draw do
  resources :cards

  root :to => 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :phrase, :pos, :translation, :word
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
require "rubygems"
require "twitter"

class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end

    


    Twitter.configure do |config|
      config.consumer_key = 'CnKtSXsUNxAXoHrQNung'
      config.consumer_secret =  'Gupq226pEt2Z3BJmjzw3soJ4Yj2kW971dRcPMtdww'
      config.oauth_token = '7941112-aOBVVlC2ei8fEBrdOkZkdJXWJVULbuZiRMeQPFZBye'
      config.oauth_token_secret = 'q8X6CAIORoPtJ16rekf6ehMvW2rb2BOtOKGfSrBYSA'
    end
    
    
  end


  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phrase %><br />
    <%= f.text_area :phrase %>
  </div>
  <div class="field">
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :pos %><br />

    <select id="card_pos" name="card[pos]" type="radio">
      <option value="0">Part of Speech</option>
      <option value="Phrase">Phrase</option>
      <option value="Verb">Verb - Verbo</option>
      <option value="Noun">Noun - Sustantivo</option>
      <option value="Pronoun">Pronoun - Pronombre</option>
      <option value="Adjective">Adjective - Adjetivo</option>
    </select>
  </div>
  </div>
  <div class="field">
    <%= f.label :translation %><br />
    <%= f.text_field :translation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<center> <h1>Notes</h1> </center>


<div id='mySwipe' style='max-width:500px;margin:0 auto' class='swipe'>
  <div class='swipe-wrap'>

    <!-- This is a thing -->

    <% @cards.each do |card| %>
      
      <div>
        <h3><%= card.word %> </h3>
        <i>
         <%= card.phrase %> 
         </i>
         <center>
         <b>POS:</b> <%= card.pos %> 
         <b>DEF:</b> <span><%= card.translation %> </span>
         
         </center>
         <center>
         <%= link_to 'Show', card %> 
         <%= link_to 'Edit', edit_card_path(card) %> 
         <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %>
          </center>
    </div>

    <% end %>

    <!-- SKSJJKSKJSJKS -->
  </div>
</div>



<div style='text-align:center;padding-top:20px;'>
  
  <button onclick='mySwipe.prev()'>prev</button> 
  <button onclick='mySwipe.next()'>next</button>

</div>

<br />


<%= link_to 'Notes', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<%

Twitter.search(@card.word, :count => 3, :result_type => "recent").results.map do |status|
  @x = "#{status.text}"
end

one_word = Twitter.search(@card.word, :lang => "es", :count => 3).results.first.text
two_word = Twitter.search(@card.word, :lang => "es", :count => 3).results.second.text
three_word = Twitter.search(@card.word, :lang => "es", :count => 3).results.last.text


%>




<p id="notice"><%= notice %></p>

<p>
  <b>Phrase:</b>
  <%= @card.phrase %>
</p>

<p>
  <b>Word:</b>
  <%= @card.word %>
</p>

<p>
  <b>Pos:</b>
  <%= @card.pos %>
</p>

<p>
  <b>Translation:</b>
  <%= @card.translation %>
</p>

<ul>
  <li><%= one_word.to_s %></li>
  <li><%= two_word %></li>
  <li><%= three_word %></li>
</ul>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwipeBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta http-equiv="X-UA-Compatible" content="IE=8">
	<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'/> 
	<link href='/style.css' rel='stylesheet'/>
	<script type="text/javascript" src="swipe.js"></script>
	<style>

	/* Swipe 2 required styles */

	.swipe {
		overflow: hidden;
		visibility: hidden;
		position: relative;
	}
	.swipe-wrap {
		overflow: hidden;
		position: relative;
	}
	.swipe-wrap > div {
		float:left;
		width:100%;
		position: relative;
	}

	/* END required styles */

	</style>
</head>





<body>

<%= yield %>


<script src='/swipe.js'></script>
<script>

// pure JS
var elem = document.getElementById('mySwipe');
window.mySwipe = Swipe(elem, {
  // startSlide: 4,
  // auto: 3000,
  // continuous: true,
  // disableScroll: true,
  // stopPropagation: true,
  // callback: function(index, element) {},
  // transitionEnd: function(index, element) {}
});

// with jQuery
// window.mySwipe = $('#mySwipe').Swipe().data('Swipe');

</script>

</body>
</html>